--- #delegateto demo
- hosts: apacheweb
  user: cca-user
  sudo: yes
  connection: ssh
  tasks: 
    - name: Run a remote ping on the appication server
      command: "ping -c 4 ans3 > /home/cca-user/ping.out"
      delegate_to: localhost 
    - name: Install a package
      yum: pkg=lynx state=latest
