--- #notify example
- hosts: apacheweb
  user: cca-user
  become: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Install appache ws
      action: yum name=httpd state=installed
      notify: Restart HTTPD
  handlers:
    - name: Restart HTTPD
      action: service name=httpd state=restarted
