--- #promt for user package
- hosts: apacheweb
  user: cca-user
  sudo: yes
  connection: ssh
  gather_facts: no
  vars:
    playbook_version: 0.01b
  vars_prompt:
    - name: pkgtoinstall
      prompt: install which package
      default: telnet
      private: no
  tasks:
    - name: Install the package
      yum: pkg={{ pkgtoinstall }} state=latest  
