--- #start at playbook example
- hosts: apacheweb
  user: cca-user
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: install telnet
      yum: pkg=telnet state=latest
    - name: install lynx
      yum: pkg=lynx state=latest
    - name: list home
      command: ls -al /home/test
      register: result
    - debug: var=result
      
