--- #tag functionality example
- hosts: apacheweb
  user: cca-user
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Install packacges
      yum: pkg={{item}} state=latest
      with_items:
        - telnet
        - lynx
      tags:
        - packages
    - name: verify telnet is isntalled
      raw: yum list installed | grep telnet > /home/cca-user/pkg.log
      tags:
        - always
