--- #UNTIL example
- hosts: apacheweb
  sudo: yes
  connection: ssh
  user: cca-user
  gather_facts: no
  tasks:
    - name: Install apache web server
      yum: pkg=httpd state=latest
    - name: Verify service status
      shell: systemctl status httpd
      register: result
      until: result.stdout.find("active (running)") != -1
      retries: 5
      delay: 5
    - debug: var=result    
